export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'a cozy reading nook in a tree trunk, digital art',
  'a futuristic cityscape with holographic advertisements, digital art',
  'a steampunk-style octopus playing the piano, illustration',
  'a minimalist poster of a vintage sci-fi movie about time travel',
  'a neon-lit alleyway in a cyberpunk city, digital art',
  'a whimsical watercolor painting of a tea party underwater',
  'a 3D render of a glass chess set on a wooden table',
  'a magical forest filled with glowing mushrooms, digital art',
  'an art deco-style poster for a jazz concert in outer space',
  'a surreal collage featuring a giraffe wearing sunglasses and a bowtie',
  'a whimsical illustration of a corgi riding a bicycle',
  'a noir-style detective scene set in a futuristic city',
  'a graffiti muralof a lion wearing a crown',
  'a chalkboard menu for a cafe on the moon',
  'an abstract painting of a city skyline at sunset',
  'an 8-bit video game character dancing in a disco',
  'a surreal painting of a fish swimming in the sky',
  'a vintage postcard from a vacation on Mars',
  'an isometric illustration of a tiny house on wheels',
  'a pop art-inspired portrait of a famous celebrity as a superhero',
  'a collage of famous landmarks from around the world',
  'a watercolor painting of a romantic scene set in Paris',
  'a 3D render of a futuristic car driving through a desert',
  'a series of minimalist posters for classic novels',
  'a retro-futuristic cityscape, digital art',
  'a hyperrealistic painting of a bowl of fruit, with a twist',
  'an illustration of a knight and a dragon playing chess',
  'a vintage-style travel poster for a trip to the center of the Earth',
  'a series of animal portraits in the style of famous artists',
  'a photorealistic illustration of an astronaut exploring a neon-lit city',
  'a whimsical map of a fictional city',
  'a psychedelic painting of a landscape with unusual colors',
  'an anime-style illustration of a group of friends on a road trip',
  'a noir comic book cover featuring a femme fatale',
  'an abstract painting inspired by the sounds of nature',
  'a collage portrait of a famous musician made from sheet music',
  'a futuristic fashion show with robot models, digital art',
  'an intricate mandala design featuring geometric shapes',
  'a 3D render of a secret garden hidden behind a waterfall',
  'a photo collage of a city skyline made from images of famous landmarks',
  'a minimalist poster for an indie film about a love story between a human and an alien',
  'a digital painting of a mythical creature in a lush, magical forest',
  'a street art mural of a cityscape at night',
  'a series of portraits of famous artists as their own famous works',
  'a watercolor painting of a serene mountain landscape',
  'an illustration of a magical library filled with floating books',
  'a surrealist painting of a man walking a tightrope between two planets',
  'a vintage travel poster for a trip to the bottom of the ocean',
  'an art nouveau-style illustration of a woman surrounded by flowers',
  'a 3D render of a futuristic city skyline with floating islands',
];
